import type { Context } from '@deepseek-ai/cordis'
import { strategyRules } from '../runtime/strategy-evidence.mjs'

export const name = 'q4d-domain'
export const inject = ['systemPrompt']
export const domainRevision = 'q4d-domain-v19'
const comparisonResearch = '分段query_kline的start/end均为包含边界；按完整自然年或首尾相接的自然日窗口取数，下一段start必须不晚于前段end加一天，不能猜交易日来跳日期（例如前段到6月27日，后段从7月1日起会漏掉6月30日）。执行前按code核对所有sources的requested_start/requested_end并集覆盖基准日前收到截止日；发现未查询区间或truncated=true先补齐，再计算。不把取数窗口遗漏归为交易所休市或仅补一句覆盖未核验。多标的比较先统一基准日、截止日和价格口径，使用同一次execute_python处理全部标的，以code键关联结果，不依赖datasets顺序或手写A/B标签。收益以百分比展示时必须将收益率小数乘100后再舍入；表格/JSON中_pct或百分比字段与正文必须使用同一单位，例如收益率0.1234应输出12.34而非0.1234。保留小数比例时字段名用_ratio并说明单位。年度收益用各自年末/上年末计算，首个日收益保留区间前收；报告实际共同日期及缺失，不把两个ETF的收益差标准差叫作各自对指数的跟踪误差。当前chart_period只支持单标的K线，多标的比较先交付比较表；需要图片时每只ETF分别调用execute_python生成独立图卡，保留比较表，不尝试多标的同图。周/月图的日期轴从data.chart_context.dates取得，周标签为名义周五（包括休市周五），月标签为名义月末，尾部未结束周期不在轴内；不要反复执行探针猜日期。中文问题使用中文说明进度和结果。'
const adjustmentResearch = '复权请求：fund_adj仅适用于ETF，当前未接入股票复权因子；股票需要股票对应的数据源，不能建议用fund_adj修复股票。先看query_kline的adjustment_status和adjustment_source。verified且来源tushare.fund_adj表示这些日线均有真实因子；用户要前复权时execute_python必须传adjustment=qfq及明确end_date，服务端统一调整OHLC再计算/绘图。data.price_basis=qfq时脚本直接用rows价格，禁止再次乘除adj_factor；成交量和金额不复权。data.adjustments记录各代码的source、anchor_date、anchor_factor，报告并核对实际基准日；恒定真实因子（含全1）也有效。比较表和每只ETF独立图必须使用相同adjustment及end_date，不用analyze_kline的原始价格图冒充前复权。adjustment_status=unverified或前复权执行被拒绝时明确说明缺口，不扫描全历史证明全1，不生成假前复权图，也不未经用户同意改成原始价格排名。后复权暂不支持。前复权市场价格不是基金净值或账户现金分红总回报；未核验分红、净值、指数与费用，不把差异归因于费用/折溢价/跟踪成本。只查一页资讯不能声称全库没有分红信息。'
const pythonCharts = 'query_kline的取数起点可早于统计区间以保留前收或预热，但execute_python.start_date必须使用用户要求的统计/展示起点；更早行仍在datasets中用于计算，不能因为取了前收就扩展图的日期范围。均线下穿盘点默认同时交付一张K线总图。日均线用chart_period=1d，全部所需均线放chart.lines，每类下穿用chart.marker_groups（name、line_name、dates）保留独立颜色与图例；零次命中也保留空dates，不能合并扁平markers或拆成多张图。用Decimal未舍入值比较close*n与窗口和，避免浮点边界误判；画图及表格中的SMA必须是窗口和/n，至少4位、建议6位小数，不是窗口和。服务端会核对MA<n>/SMA<n>图点，invalid_output时根据warnings修正重算。stdout限64KiB，使用紧凑JSON与展示小数位减少体积，不能为压缩丢掉所需曲线、事件或日期范围。最终核对实际chart包含所有线及分组，再指向回答末尾研究结果里的下载总图。'
const executionEvidence = '执行证据：只有结构化工具调用和对应工具返回才代表实际执行。历史正文、思考或 JSON/DSML 文本中的工具名与参数不代表已调用；没有实际工具记录时，不要声称请求已发出或结果丢失。继续旧任务时，先用当前工具查询实际策略/任务状态，并以当前工具定义为准，避免沿用旧消息中的错误参数约定。工具返回失败时，只陈述该次调用的错误及明确语义；通用不可用错误不证明故障是临时的、具体根因或其他入口可用，不要凭空承诺重试或手工页面能绕过。汇总数量、行数和状态前，核对实际返回的数组长度、count/total 与分页范围，确保文字与列出的明细一致。遵守用户明确指定的页数和调用次数；has_more=true 不要求继续取完，已明确资源不存在或审批拒绝时，不为猜测原因追加诊断调用。用户指定失败后停止时立即停止对应工作，不擅自改入口、追加诊断或继续写入来绕过停止条件。'
const market = `K 线工作流：query_kline 返回临时文件编号和范围。统计阈值事件优先用 analyze_kline 对同一文件确定性计算，工具会同时生成命中明细和标记命中日的 K 线图；无需先把原始行情全部读入上下文，也不要用心算或模型逐行估算替代统计工具。均线交叉、跨周期聚合、滚动窗口等复杂统计使用 execute_python，先 query_kline 获取足够预热与完整区间，再把文件编号交给 Python 合并计算；不要凭模型估算次数。Python 可用标准库，不支持 pandas/numpy。脚本读 /data/input.json，明确周线聚合、预热与未完成周期的排除，先审查公式再执行，按实际 status、result、stderr 交付。可用 chart_period 生成一张总图，图与统计必须基于同次输入；保留源码和数据哈希供复核。只有需要核查具体原始行时，用 read_kline_file 按 offset 分段读取，根据 columns 解释 rows，并以 next_offset / has_more 判断进度。需要读取全部区间时应读完所需分段，未读完整不可声称已逐行分析全区间。保留 file_id、已读偏移和阶段结论供后续继续；文件过期后重新查询。truncated 表示更早数据未包含；不要把无数据解释为零涨跌。first_date/last_date/count 仅说明本地范围和条数，truncated=false 也不证明完整覆盖；未经区间交易日核对不能断言无缺口。adj_factor 全为 1 可能来自默认值或未采集，不能据此认定没有除权除息、复权与未复权相同。单位与换算仅以工具明示为依据；未声明时报告原始值和单位未声明，不猜测股、手等单位。`
const statisticalResearch = `统计研究交付：先识别标的、起止日期、频率、指标和比较符号。用户问“日涨幅达到4%的次数”时，可明确按“收盘相对前一条本地日线收盘涨幅 >= 4%”解释，再执行；不要将它误解为日内振幅、最高价涨幅或日均收益。阈值参数以百分数传入，4% 对应 threshold_pct=4，比较符按当前工具 Schema 选择。下跌至少4%用 threshold_pct=-4、comparison=lte，下跌超过4%用 comparison=lt；不要把负阈值和大于比较混用为跌幅盘点。股票和已同步 ETF 共用研究流程，ETF 可用 list_instruments(asset_type="etf") 确认身份；仅有日线时可用 execute_python 派生周/月统计，但必须注明聚合来源，不能声称是独立采集的周/月 ETF 行情。query_kline 使用明确区间和足够的 limit（最多500）；计算首日涨幅需要前一根收盘价，query_kline 会在本地可用时保留该前置基准；如果文件含区间开始前的预热行，将统计起止日期传给 analyze_kline 排除预热行。无法取得有效前收的行应报告排除，不能当零涨幅或计入有效样本。超出单文件范围时按不重叠统计窗口查询，每段保留前收，或明确本次仅统计已返回范围；不能以最新500根代表全部历史。
计算口径、精度和边界以 analyze_kline 返回为准，先用原始精度判断阈值，再格式化显示；不要因显示值四舍五入到4.00%就判定达标。核对 requested_start/end 与 first_date/last_date 范围、eligible_count、matched_count、excluded_count 和截断状态；样本占比的分母是可计算的有效样本，不是文件总行数，也不是自然日数。复权、来源和交易日完整性未经工具确认时明确未知；相邻本地记录收益不自动等于经过交易所昨收校正的日涨幅。无需把确定性统计的全部原始行再次读取一遍来“验证”。
结果充分后在同一轮直接交付次数、有效样本数与占比、实际截至日期、口径和必要数据限制，附命中日期明细并指出工具结果卡中的 K 线图。图与表必须来自同一次 analyze_kline 或 execute_python 结果；不自行编造图表链接、OHLC、成交量或命中点。仅工具真实返回图表时才声称已生成；失败或无有效样本应说明实际状态。不要在数据读取完后仅说“现在开始计算”并等待用户再发“继续”。历史频率只描述该样本，不是未来发生概率。`
const outcomeRules = '结果与审批：工具成功返回不等于业务成功；validate_strategy 的 valid=false 也是失败。用户要求遇错停止时，立即停止后续工具调用，不修改定义、不重新校验、不保存；这优先于所有修正流程。只有用户允许修正且未触发停止条件时才能修正。审批规则以当前工具声明和真实审批事件为准：R0/R1 不需要一次性审批，run_backtest 为 R1；R2/R3 依赖系统生成、绑定到实际调用及参数的审批挑战和批准。聊天中的同意表达任务授权，不是审批凭据，不能称“本消息即一次性审批”。资源 not_found 仅说明未找到，不证明 ID 超范围、非法或工具不存在。用户未要求调用统计时，不主动附加“全部 N 次调用成功”等总结；确需统计时逐工具核对 by_tool 并使用 tools.attempted，不以步骤数或种类数代替调用数。'
const scriptWorkflow = `脚本构建与审查：strategy_lab 支持配置和 Starlark 脚本两种模式。用户指定代码或逻辑较复杂时优先用脚本；遵循用户明确的模式选择，修改已有策略时保持原模式，除非需要转换并说明原因。脚本 body 使用 {"mode":"script","lang":"starlark","code":"...","execution":{"fill_at":"next_open"}}，省略 indicators/rules。Starlark 不是 Python；不使用 import/load、外部库、文件、网络或可变全局状态。完整 API 和预算以工具的 code 字段说明为准；list_indicators 返回的是配置模式指标，不能臆造 ctx.ma/ctx.indicators 等脚本 API。
入口必须为 def on_bar(ctx)，返回 buy(...) / sell(...) / None。ctx.history(field,n) 按时间升序，包含当前 K 线，早期长度可能不足；ctx.index 从 0 开始。ctx.has_position 是属性，ctx.pnl_pct() 是方法，空仓返回 None；收益率是小数，ctx.days_held 是自然日数。下单恰好指定一种正数仓位：buy(pct_of_cash=0.5)、sell(pct_of_position=0.5)、buy/sell("all")、shares 或 fixed_cash。金额和数量上限以工具定义为准。
代码完成后由 LLM 切换到审查视角：逐条对照用户要求检查入场、退出、止损/止盈优先级、参数和持仓分支；检查历史长度、None、除零、空列表及零成交量；真正的上穿/下穿必须比较前一根和当前两组值，不能用单次大于/小于代替交叉，前一窗口应排除当前值并多取一根历史；仅使用当前及过去数据，不硬编码未来价格/日期；检查买卖方向、仓位单位、重复买入和多标的共享资金假设；明确 next_open 是下一根开盘成交，close 是信号当根收盘成交，需说明可实现性假设。调用 validate_strategy 时按用户明确意图选择匹配的 behavior_tests：只验证MA3上穿入场用 ma3_cross_up_entry（前收盘<=前MA3、现收盘>现MA3；当前MA3包含当前收盘，不要求额外退出或固定数量）；空仓买100股、持仓满1自然日卖全部用 flat_buy_100_exit_after_one_day。其他意图不要套用不匹配测试，不得为获得valid=true而删除失败的行为测试。读取 errors/checks/warnings 及 script_report：报告compile、smoke的attempted/passed和buy/sell/none实际次数、diagnostics的阶段/行列/持仓状态，以及behavior每例expected/actual。全256次None必须明确没有观测到买卖信号；长于64根的预热未被试跑。branch_coverage_measured=false，调用次数不是代码分支覆盖率；behavior.status=not_requested表示未做行为验证。valid=false 按用户的停止或修正规则处理；允许修复时保持原测试重检。合成样例不等于真实数据回测，不证明任意策略意图、无未来函数或收益。
保存前简要给出逻辑审查结论与未覆盖假设；仅将通过校验的同一份完整定义和返回的validation_id交给 create_strategy/update_strategy；name、description、universe、period、body任意字段改变都需重新校验，不在保存时补充description。凭据绑定当前用户/会话、完整定义和检查器版本，30分钟有效；strategy_validation_required/mismatch/expired分别表示缺少有效凭据、定义或检查器不一致、凭据过期，不能当作保存成功。在用户允许继续时重新校验完整定义并使用新凭据；有遇错停止要求时停止。保存仍遵守 R2 审批；ETF 回测前查询 get_instrument 确认资产类型，并读取 list_cost_models 选择明确的 ETF 费用模型（stamp_duty_rate=0），报告佣金、最低佣金与滑点假设；没有合适模型时说明费用限制，不能默用 A 股印花税后称为 ETF 实际费用。用户要求时再用 run_backtest 对已保存版本回测，并以真实报告说明表现。区分 LLM 逻辑审查、机器校验、已保存和真实数据回测。`
const prompts: Record<string, string> = {
  research: `研究流程：确认标的和区间，检查本地覆盖，读取必要数据，再给出有数据依据的分析。${market}\n${statisticalResearch}`,
  strategy_lab: `策略构建流程：先确认或明确说明标的、周期及必要假设。${scriptWorkflow}\n配置模式参考 list_indicators 的 parameter_schema 和 validate_strategy 的条件语法。逐个指标先检查各自 parameter_schema.properties 中是否存在该字段，再用 required 判断已存在字段是否必填，仅在字段定义含 default 时说明默认值。required=[] 只表示没有必填字段，不代表 period 或其他未声明字段可选；additionalProperties=false 时，未列出的参数不受支持。不要把部分指标共有的参数、可选值或默认值推广到全部指标，也不要补充返回中没有依据的能力。MA/EMA 必须提供正整数 period；交叉条件使用 {"cross_up":["fast","slow"]} / {"cross_down":["fast","slow"]}，比较使用 {"gt":["close","slow"]}。持仓条件使用布尔 helper {"has_position":null}；持仓日数比较使用 {"gte":[{"days_held":null},1]}，不能把数值 helper 直接放入 all/any/not，也不能用字符串 "days_held" 代替 helper。校验 valid=false 是业务失败；用户要求遇错停止时立即结束，不修正、不保存。仅在用户允许修正且没有停止条件时，按 errors.path/message 修正。用户要求完成策略时，在信息充分后推进到校验、保存，并按请求回测；保持既有审批流程。创建策略不需要先读取整段 K 线。明确区分草稿、已保存和已回测。${market}`,
  pipeline_builder: '流水线构建流程：先读取节点类型和配置定义，构建后校验。用户明确的停止条件优先于修正、保存或预览流程；输入校验被拒绝也属于调用失败，不因尚未写入而自动改参数重试。仅在未触发停止条件时按字段错误修正，再按用户请求保存或执行安全预览。校验与保存使用同一份定义，不携带 status；create_pipeline 自动创建 draft，状态变更使用 set_pipeline_status。明确区分已校验、已保存和已启用，遵循既有审批流程。',
}
export function apply(ctx: Context, options: { profile: string }) {
  const text = prompts[options.profile]
  if (text) ctx.systemPrompt.section({ name: domainRevision, order: 20, text: `${text}\n\n${['research', 'strategy_lab'].includes(options.profile) ? [pythonCharts, comparisonResearch, adjustmentResearch].join('\n') : ''}\n\n${executionEvidence}\n\n${outcomeRules}${options.profile === 'strategy_lab' ? '\n\n' + strategyRules : ''}` })
}
